### ISSUE TITLE
Shade dependencies

### ISSUE THREAD

**Issue by mstump** [gkatzioura/CloudStorageMaven#1]
First, thank you for this project. I'm trying to use it in gradle to upload artifacts to GCS but i'm getting conflicts between the guava pulled in by your project and transitive dependencies I think from the maven plugin. Can we shade the dependencies for this project?

```
Caused by: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
        at com.google.cloud.storage.StorageImpl.optionMap(StorageImpl.java:1028)
        at com.google.cloud.storage.StorageImpl.optionMap(StorageImpl.java:1020)
        at com.google.cloud.storage.StorageImpl.optionMap(StorageImpl.java:1050)
        at com.google.cloud.storage.StorageImpl.list(StorageImpl.java:257)
        at com.gkatzioura.maven.cloud.gcs.GoogleStorageRepository.connect(GoogleStorageRepository.java:55)
        at com.gkatzioura.maven.cloud.gcs.GoogleStorageWagon.connect(GoogleStorageWagon.java:135)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.connectWagon(WagonRepositoryConnector.java:345)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.pollWagon(WagonRepositoryConnector.java:385)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:803)
        at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:467)
...
```

**Comment by gkatzioura** [comment]
Changes merged. New version 1.2 has the fix.
