### ISSUE TITLE
Anonymous caller does not have storage.objects.list access to XXX.

### ISSUE THREAD

**Issue by wheredevel** [gkatzioura/CloudStorageMaven#53]
I followed the google-storage-wagon [tutorial](https://egkatzioura.com/2018/04/09/host-your-maven-artifacts-using-google-cloud-storage/).

Tried with 
```
gcloud auth application-default login
```
Tried setting the environment variable
```
GOOGLE_APPLICATION_CREDENTIALS=/path/xxx.json
```
Tried different plugin versions from 1.0 to 1.8.. 2.0.
Nothing works.
I'm still getting the following exception:  
```
Caused by: com.vorstella.shade.com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
{
  "code" : 401,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "Anonymous caller does not have storage.objects.list access to XXX.",
    "reason" : "required"
  } ],
  "message" : "Anonymous caller does not have storage.objects.list access to XXX."
}
	at com.vorstella.shade.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.vorstella.shade.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.vorstella.shade.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.vorstella.shade.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:401)
	at com.vorstella.shade.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1097)
	at com.vorstella.shade.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:499)
	at com.vorstella.shade.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:432)
	at com.vorstella.shade.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:549)
	at com.vorstella.shade.com.google.cloud.storage.spi.v1.HttpStorageRpc.list(HttpStorageRpc.java:356)
	... 76 more
```
gcloud/gsutil - both work properly.

Why does the plugin keep trying to connect Anonymously?  
Please, help!

**Comment by gkatzioura** [comment]
It seems there is an issue with the key
GOOGLE_APPLICATION_CREDENTIALS=/path/xxx.json

Validated in another machine. Gsutil might even pick you already existing local configuration
